---
- name: Check user login from secure files on all servers
  hosts: test
  become: true
  gather_facts: true
  vars:
    users:
      - "nizam.osman"
      - "rajadino"
      - "adif.firdaus"
      - "ummi.fhana"
  tasks:
    - name: Search for login events for multiple users in secure logs
      shell: |
        cat /var/log/secure* | grep -E "Accepted password for ({{ users | join('|') }})" || true
      register: login_results
      ignore_errors: yes

    - name: Format and save login results to a file on remote server
      shell: |
        echo "Server {{ inventory_hostname }}" > /home/adif.firdaus/{{ inventory_hostname }}_login_results.txt
        {% if login_results.stdout_lines %}
        {% for line in login_results.stdout_lines %}
        echo "{{ line.split()[8] }} {{ ' '.join(line.split()[0:8] + line.split()[9:]) }}" >> /home/adif.firdaus/{{ inventory_hostname }}_login_results.txt
        {% endfor %}
        {% else %}
        echo "No Login" >> /home/adif.firdaus/{{ inventory_hostname }}_login_results.txt
        {% endif %}

    - name: Fetch file from remote servers
      fetch:
        src: /home/adif.firdaus/{{ inventory_hostname }}_login_results.txt
        dest: /home/ansible/collected_files/login/login_{{ inventory_hostname }}_login_results.txt
        flat: true

    - name: Delete file from remote servers
      file:
        path: /home/adif.firdaus/{{ inventory_hostname }}_login_results.txt
        state: absent

- name: Merge collected files
  hosts: localhost
  tasks:
    - name: Combine IP files into a single file with blank line between servers
      shell: |
        for file in /home/ansible/collected_files/login/login_*; do
          cat "$file" >> /home/ansible/collected_files/login/merged_files.txt
          printf "\n" >> /home/ansible/collected_files/login/merged_files.txt  # Add a blank line after each entry
        done

    - name: Delete files starting with 'login' locally
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - /home/ansible/collected_files/login/login*
