# Change user password
- name: Change user password
  hosts: linux
  become: true
  vars_files:
    - vault.yml
    
  vars:
    username: dino
    user_password: "{{ 'password123' | password_hash('sha512') }}"
  
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        state: present
