# Create single user for redhat server
- name: create new user
  hosts: redhat
  become: true
  vars_files:
    - vault.yml
    
  vars:
    username: ansUser
    user_password: "{{ 'password' | password_hash('sha512') }}"
  
  tasks:
    - name: create new user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        state: present
        shell: /bin/bash
        groups: "wheel"
        create_home: true
